# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 472732af7701f72faa0342223feeb1c19f0ecae9227b612e180d282750faceb4e485559d7803879c86ea144bb4121c2ff89797bddacc7b96ebf8c9f819c456b0

test:
  secret_key_base: 5a6184fad82a12797507b69e19edcec58dc16a8d46b0a726cd2ae57dca9564e6a7f1205e978da9a1653eca02a3049ecb92a2a765a26090f41ece97709958a46e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
